### ISSUE TITLE
ActiveButton shows part of it outside the window(title bar)

### ISSUE THREAD

**Issue by alanackart** [TheCodeKing/ActiveButtons.Net#3]
Sir, I found that ActiveButton shows small part of it outside the window(title bar), ![capture](https://cloud.githubusercontent.com/assets/18682922/25024105/344d0e4c-20cf-11e7-9b3f-c34fd2e3a133.JPG) and I can not fix it by changing its Location. How can I solve this problem? 

I am looking for your early reply.(I am using Windows 10 now)

**Comment by TheCodeKing** [comment]
This was written a long time ago and not being updated to support recent Windows versions. If you want to implement a fix and submit a pull request, take a look at [ActiveMenuImpl.cs](https://github.com/TheCodeKing/ActiveButtons.Net/blob/master/Source/Controls/ActiveMenuImpl.cs)

**Comment by alanackart** [comment]
Thank for your reply. I would look deep into the code and try to fix it once I have time.

**Comment by patv2learn** [comment]
@alanackart were you able to make this fix? I have tried to add 40px offset and that looks good but I would like to know if there is any better way for W10 generic? Thanks.
